# Site settings
title: Freelancer
email: your-email@domain.com
description: "Jordan Presnick is a user experience designer in San Francisco."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jordanpresnick
  - title: twitter
    url: http://twitter.com/jordanpresnick
  - title: github
    url: http://github.com/jord0

# Build settings
markdown: kramdown
permalink: pretty
